#[cfg(test)]
mod test {
    use super::*;
    use clap::{Parser, ValueEnum};
    use insta::{assert_debug_snapshot, assert_snapshot};
    use pong::Cli;
    use pong::{creation_pongs, display, rgb, World};
    use rand::rngs::StdRng;
    use rand::rngs::ThreadRng;
    use rand::SeedableRng;
    use std::time::Instant;
    use window_rs::WindowBuffer;

    #[test]
    fn test_rgb() {
        assert_eq!(rgb(0, 0, 0), 0x00_00_00_00);
        assert_eq!(rgb(255, 255, 255), 0x00_ff_ff_ff);
        assert_eq!(rgb(0x12, 0x34, 0x56), 0x00_12_34_56);
    }

    #[test]
    fn pong_generation() {
        let mut buffer: WindowBuffer = WindowBuffer::new(5, 20);

        let mut game_elements: World = pong::World::new(
            Vec::new(),
            Vec::new(),
            0,
            0,
            pong::Direction::Still,
            pong::Direction::Still,
            Some((buffer.width() / 2, buffer.height() / 2)),
            pong::BallDirection::Still,
            false,
            Instant::now(),
            0,
            0,
            0,
            StdRng::seed_from_u64(75),
        );

        creation_pongs(&mut game_elements, &buffer);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        .....
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #.#.#
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        "###
        );
    }

    #[test]
    #[ignore]
    fn pongs_movements() {
        let cli = pong::Cli::parse();
        let mut buffer: WindowBuffer = WindowBuffer::new(5, 25);
        let mut instant_ball = Instant::now();
        let mut instant_pong = Instant::now();

        let mut game_elements: World = pong::World::new(
            Vec::new(),
            Vec::new(),
            0,
            0,
            pong::Direction::Still,
            pong::Direction::Still,
            Some((buffer.width() / 2, buffer.height() / 2)),
            pong::BallDirection::Still,
            false,
            Instant::now(),
            0,
            cli.pong_speed,
            cli.ball_speed,
            StdRng::seed_from_u64(75),
        );

        creation_pongs(&mut game_elements, &buffer);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        .....
        .....
        .....
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #.#.#
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        "###
        );

        game_elements.player_1_direction = pong::Direction::North;
        game_elements.player_2_direction = pong::Direction::South;
        game_elements.update(&mut buffer, &cli, &mut instant_pong, &mut instant_ball);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        .....
        .....
        #....
        #....
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        ..#.#
        ....#
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        "###
        );

        game_elements.update(&mut buffer, &cli, &mut instant_pong, &mut instant_ball);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        .....
        #....
        #....
        #....
        #....
        #...#
        #...#
        #...#
        #...#
        #...#
        #...#
        ....#
        ..#.#
        ....#
        ....#
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        "###
        );

        game_elements.update(&mut buffer, &cli, &mut instant_pong, &mut instant_ball);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        #....
        #....
        #....
        #....
        #....
        #....
        #...#
        #...#
        #...#
        #...#
        ....#
        ....#
        ..#.#
        ....#
        ....#
        ....#
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        .....
        "###
        );
    }

    #[test]
    fn ball_launch_right() {
        let cli = pong::Cli::parse();
        let mut buffer: WindowBuffer = WindowBuffer::new(15, 10);

        let mut game_elements: World = pong::World::new(
            Vec::new(),
            Vec::new(),
            0,
            0,
            pong::Direction::Still,
            pong::Direction::Still,
            Some((buffer.width() / 2, buffer.height() / 2)),
            pong::BallDirection::Still,
            false,
            Instant::now(),
            0,
            cli.pong_speed,
            cli.ball_speed,
            StdRng::seed_from_u64(75),
        );

        game_elements.ball_movement(&mut buffer, &cli);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        ...............
        ...............
        ...............
        ...............
        ...............
        ........#......
        ...............
        ...............
        ...............
        ...............
        "###
        );

        game_elements.ball_movement(&mut buffer, &cli);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        ...............
        ...............
        ...............
        ...............
        ...............
        .........#.....
        ...............
        ...............
        ...............
        ...............
        "###
        );

        game_elements.ball_movement(&mut buffer, &cli);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        ...............
        ...............
        ...............
        ...............
        ...............
        ..........#....
        ...............
        ...............
        ...............
        ...............
        "###
        );

        game_elements.ball_movement(&mut buffer, &cli);
        display(&game_elements, &mut buffer);

        assert_snapshot!(
            buffer.to_string(),
            @r###"
        ...............
        ...............
        ...............
        ...............
        ...............
        ...........#...
        ...............
        ...............
        ...............
        ...............
        "###
        );
    }
}
